# Generated by Django 4.2.30 on 2026-04-25 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('anamnesis', models.TextField(verbose_name='Anamnesis')),
                ('physical_exam', models.TextField(verbose_name='Exploración física')),
                ('diagnosis', models.TextField(verbose_name='Diagnóstico')),
                ('treatment_plan', models.TextField(verbose_name='Plan de tratamiento')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso (kg)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia cardíaca (lpm)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation', to='appointments.appointment', verbose_name='Cita')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient', verbose_name='Paciente')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Veterinario')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('active_ingredient', models.CharField(blank=True, max_length=150, verbose_name='Principio activo')),
                ('presentation', models.CharField(blank=True, max_length=100, verbose_name='Presentación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Medicamento (catálogo)',
                'verbose_name_plural': 'Medicamentos (catálogo)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Indicaciones generales')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medical.consultation', verbose_name='Consulta')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Emitido por')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Laboratorio')),
                ('disease', models.CharField(max_length=150, verbose_name='Enfermedad que previene')),
                ('recommended_schedule', models.TextField(blank=True, verbose_name='Esquema recomendado')),
            ],
            options={
                'verbose_name': 'Vacuna (catálogo)',
                'verbose_name_plural': 'Vacunas (catálogo)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VitalsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(verbose_name='Fecha y hora')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso (kg)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='FC (lpm)')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals_history', to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Signos vitales',
                'verbose_name_plural': 'Historial de signos vitales',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField(verbose_name='Fecha de aplicación')),
                ('lot', models.CharField(blank=True, max_length=50, verbose_name='Lote')),
                ('expiration', models.DateField(blank=True, null=True, verbose_name='Caducidad del lote')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Próxima dosis')),
                ('application_site', models.CharField(blank=True, max_length=100, verbose_name='Sitio de aplicación')),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Aplicado por')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='patients.patient', verbose_name='Paciente')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medical.vaccine', verbose_name='Vacuna')),
            ],
            options={
                'verbose_name': 'Registro de vacunación',
                'verbose_name_plural': 'Registros de vacunación',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(max_length=100, verbose_name='Dosis')),
                ('frequency', models.CharField(max_length=100, verbose_name='Frecuencia')),
                ('duration', models.CharField(max_length=100, verbose_name='Duración')),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('topical', 'Tópica'), ('iv', 'Intravenosa'), ('im', 'Intramuscular'), ('sc', 'Subcutánea'), ('ophthalmic', 'Oftálmica'), ('other', 'Otra')], default='oral', max_length=15, verbose_name='Vía de administración')),
                ('instructions', models.TextField(blank=True, verbose_name='Instrucciones adicionales')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medical.medication', verbose_name='Medicamento')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medical.prescription', verbose_name='Receta')),
            ],
            options={
                'verbose_name': 'Ítem de receta',
                'verbose_name_plural': 'Ítems de receta',
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=150, verbose_name='Nombre del estudio')),
                ('result', models.TextField(verbose_name='Resultado / interpretación')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='lab_results/', verbose_name='Archivo adjunto')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Ordenado por')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Resultado de laboratorio',
                'verbose_name_plural': 'Resultados de laboratorio',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalVaccinationRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('application_date', models.DateField(verbose_name='Fecha de aplicación')),
                ('lot', models.CharField(blank=True, max_length=50, verbose_name='Lote')),
                ('expiration', models.DateField(blank=True, null=True, verbose_name='Caducidad del lote')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Próxima dosis')),
                ('application_site', models.CharField(blank=True, max_length=100, verbose_name='Sitio de aplicación')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('applied_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Aplicado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient', verbose_name='Paciente')),
                ('vaccine', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='medical.vaccine', verbose_name='Vacuna')),
            ],
            options={
                'verbose_name': 'historical Registro de vacunación',
                'verbose_name_plural': 'historical Registros de vacunación',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPrescription',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('issued_at', models.DateTimeField(blank=True, editable=False)),
                ('notes', models.TextField(blank=True, verbose_name='Indicaciones generales')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('consultation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='medical.consultation', verbose_name='Consulta')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Emitido por')),
            ],
            options={
                'verbose_name': 'historical Receta',
                'verbose_name_plural': 'historical Recetas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLabResult',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('test_name', models.CharField(max_length=150, verbose_name='Nombre del estudio')),
                ('result', models.TextField(verbose_name='Resultado / interpretación')),
                ('attachment', models.TextField(blank=True, max_length=100, null=True, verbose_name='Archivo adjunto')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ordered_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ordenado por')),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'historical Resultado de laboratorio',
                'verbose_name_plural': 'historical Resultados de laboratorio',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalConsultation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('anamnesis', models.TextField(verbose_name='Anamnesis')),
                ('physical_exam', models.TextField(verbose_name='Exploración física')),
                ('diagnosis', models.TextField(verbose_name='Diagnóstico')),
                ('treatment_plan', models.TextField(verbose_name='Plan de tratamiento')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso (kg)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia cardíaca (lpm)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('appointment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appointments.appointment', verbose_name='Cita')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient', verbose_name='Paciente')),
                ('vet', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Veterinario')),
            ],
            options={
                'verbose_name': 'historical Consulta',
                'verbose_name_plural': 'historical Consultas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
