# Generated by Django 4.2.30 on 2026-05-07 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dewormer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Laboratorio')),
                ('type', models.CharField(choices=[('internal', 'Interno'), ('external', 'Externo'), ('both', 'Ambos')], default='internal', max_length=10, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Desparasitante (catálogo)',
                'verbose_name_plural': 'Desparasitantes (catálogo)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDewormingRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso (kg)')),
                ('lot', models.CharField(blank=True, max_length=50, verbose_name='Lote')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Próx. dosis')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('applied_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Aplicado por')),
                ('dewormer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='medical.dewormer', verbose_name='Desparasitante')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'historical Registro de desparasitación',
                'verbose_name_plural': 'historical Registros de desparasitación',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DewormingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso (kg)')),
                ('lot', models.CharField(blank=True, max_length=50, verbose_name='Lote')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Próx. dosis')),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Aplicado por')),
                ('dewormer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medical.dewormer', verbose_name='Desparasitante')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dewormings', to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Registro de desparasitación',
                'verbose_name_plural': 'Registros de desparasitación',
                'ordering': ['-date'],
            },
        ),
    ]
