# Generated by Django 4.2.30 on 2026-04-25 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('product_type', models.CharField(choices=[('medicine', 'Medicamento'), ('vaccine', 'Vacuna'), ('supply', 'Insumo / Material')], max_length=15, verbose_name='Tipo')),
                ('unit', models.CharField(max_length=30, verbose_name='Unidad de medida')),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock actual')),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock mínimo (alerta)')),
                ('lot', models.CharField(blank=True, max_length=50, verbose_name='Lote')),
                ('expiration', models.DateField(blank=True, null=True, verbose_name='Caducidad')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('purchase', 'Compra / Entrada'), ('vaccination', 'Vacunación aplicada'), ('prescription', 'Dispensación en receta'), ('adjustment', 'Ajuste manual'), ('expiry', 'Baja por caducidad')], max_length=15, verbose_name='Motivo')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad (+/-)')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
