# Generated by Django 4.2.30 on 2026-04-25 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('consultation', 'Consulta'), ('vaccination', 'Vacunación'), ('surgery', 'Cirugía'), ('grooming', 'Estética'), ('followup', 'Seguimiento'), ('emergency', 'Emergencia')], max_length=20, unique=True, verbose_name='Clave')),
                ('label', models.CharField(max_length=50, verbose_name='Etiqueta')),
                ('color', models.CharField(default='#0d6efd', max_length=7, verbose_name='Color (hex)')),
                ('default_duration', models.PositiveIntegerField(default=30, verbose_name='Duración predeterminada (min)')),
            ],
            options={
                'verbose_name': 'Tipo de cita',
                'verbose_name_plural': 'Tipos de cita',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(verbose_name='Fecha y hora')),
                ('duration', models.PositiveIntegerField(default=30, verbose_name='Duración (min)')),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('confirmed', 'Confirmada'), ('in_progress', 'En curso'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no_show', 'No se presentó')], default='scheduled', max_length=15, verbose_name='Estado')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo de consulta')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.appointmenttype', verbose_name='Tipo')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='Paciente')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Veterinario')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
