# Generated by Django 4.2.30 on 2026-04-25 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Raza')),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('id_document', models.CharField(blank=True, max_length=20, verbose_name='CURP / RFC')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('emergency_contact', models.CharField(blank=True, max_length=150, verbose_name='Contacto de emergencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Especie')),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('sex', models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra')], max_length=1, verbose_name='Sexo')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso actual (kg)')),
                ('color', models.CharField(blank=True, max_length=80, verbose_name='Color / pelaje')),
                ('microchip_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Microchip')),
                ('neutered', models.BooleanField(default=False, verbose_name='Esterilizado/a')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patients/photos/', verbose_name='Foto')),
                ('allergies', models.TextField(blank=True, verbose_name='Alergias conocidas')),
                ('chronic_conditions', models.TextField(blank=True, verbose_name='Condiciones crónicas')),
                ('deceased', models.BooleanField(default=False, verbose_name='Fallecido')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Fecha de fallecimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.breed', verbose_name='Raza')),
                ('father', models.ForeignKey(blank=True, limit_choices_to={'sex': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paternal_offspring', to='patients.patient', verbose_name='Padre')),
                ('mother', models.ForeignKey(blank=True, limit_choices_to={'sex': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maternal_offspring', to='patients.patient', verbose_name='Madre')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='patients.owner', verbose_name='Propietario')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.species', verbose_name='Especie')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='breed',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='patients.species', verbose_name='Especie'),
        ),
        migrations.AlterUniqueTogether(
            name='breed',
            unique_together={('species', 'name')},
        ),
    ]
